
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: rjw_admin
    password: Rjw19980411
    url: jdbc:mysql://rm-2ze051phm81h4k7v4so.mysql.rds.aliyuncs.com:3306/educ
  #Logback:
  log:
    file:
      path: ./logs/${spring.application.name}/${spring.profiles.active} # 日志-文件路径
      maxKeep: 5  # 最大保留的文件个数

aliyun:
  ossConfig:
    bucketName: educ-rjw
    endpoint: oss-cn-hangzhou.aliyuncs.com
    accessKeyId: LTAI5tK5Gan1hbb9BYjJ2cdy
    accessKeySecret: MxSHuYTzXtZMKeR1lG5VxehpVvdRKH
    avatarFilePath: educ/avatar/
#mybatis日志
#mybatis-plus:
#  configuration:
#  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
